version: "3.9"

services:
  web:
    user: "1000"
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./controller/.env
    links:
      - db:db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/db/
    environment:
      - POSTGRES_PASSWORD=superadmin
      - POSTGRES_DB=proyectois2
    ports:
      - 5432:5432

volumes:
  postgres_data:
