# This is a basic workflow to help you get started with Actions

name: Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Installing dependecies
        run:
          ./install.sh
        shell:
          bash
        env:
          TOKEN: '${{ secrets.env }}'
      - name: Testing backend
        run:
          ./backend-test.sh
        shell:
          bash
        env:
          TOKEN: '${{ secrets.env }}'
      - name: Starting backend
        run:
          ./backend.sh > /dev/null 2>&1 & 
        shell:
          bash
        env:
          TOKEN: '${{ secrets.env }}'
      - name: Testing frontend
        env:
          TOKEN: '${{ secrets.env }}'
        working-directory:
          ./frontend
        run:
          CI=true npm run test --watchAll
        shell:
          bash
        
